name: Build & Push smart contract
 
jobs:
  build-push:
    name: "Build & push smart contract"
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [lts/*]

    # Checkout source code
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # Setup Nodejs
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    # Setup yarn
    - name: Install yarn
      run: npm install -g yarn
      
    # Cache dependencies for faster build time in future
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ./node_modules
          ./.yarn
        key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}

    # Install GYP as build dependencies
    - name: Install GYP
      run: |
        npm install node-gyp -g
        npm install node-gyp-build -g
    # Install project dependencies
    - name: Install dependencies
      run: |
        yarn install --prefer-offline --pure-lockfile --cache-folder .yarn --modules-folder node_modules
    # Configure Git informations
    - name: Configure Git informations
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
   
    # Build the contracts
    - name: Build contracts
      run: |
        yarn build
